modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/Insane96/MobsPropertiesRandomness/issues"
[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://www.curseforge.com/minecraft/mc-mods/mobs-properties-randomness"
logoFile="logo.png"
credits="Crafttweaker for the custom logger"
authors="${mod_authors}"
displayTest="IGNORE_SERVER_VERSION"

description='''${mod_description}'''

[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="insanelib"
    mandatory=true
    versionRange="${lib_version_range}"
    ordering="NONE"
    side="BOTH"