modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/Insane96/MobsPropertiesRandomness/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://www.curseforge.com/minecraft/mc-mods/mobs-properties-randomness"
logoFile="icon.png"
authors="Insane96MCP"
description='''
Change many properties to mobs on spawn, and on other events (e.g. on attack, on death). Change properties like attributes, potion effects, sounds, loot tables, and much more. Or create presets for a mob to spawn with. All with data packs.
'''

[[mixins]]
config="${mod_id}.mixins.json"

# The [[accessTransformers]] block allows you to declare where your AT file is.
# If this block is omitted, a fallback attempt will be made to load an AT from META-INF/accesstransformer.cfg
#[[accessTransformers]]
#file="META-INF/accesstransformer.cfg"

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="insanelib"
    type="required"
    versionRange="${insanelib_version_range}"
    ordering="NONE"
    side="BOTH"